// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANFS92SzmC5adm44UXdQ4KCeegeYe9yvM',
    appId: '1:470125849375:web:6c20a41e17e1adede21e2a',
    messagingSenderId: '470125849375',
    projectId: 'adventureworks-61518',
    authDomain: 'adventureworks-61518.firebaseapp.com',
    storageBucket: 'adventureworks-61518.firebasestorage.app',
    measurementId: 'G-Y3ZMWZLYFM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDb05RZMRAMpKC1oiMJdoHrQbK_rxDpYsc',
    appId: '1:470125849375:android:c69c02d51cf47fe9e21e2a',
    messagingSenderId: '470125849375',
    projectId: 'adventureworks-61518',
    storageBucket: 'adventureworks-61518.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXpAz9PLjYdiG6mxoPq3Mdxc698nqC6Jc',
    appId: '1:470125849375:ios:476a53508c56f95ae21e2a',
    messagingSenderId: '470125849375',
    projectId: 'adventureworks-61518',
    storageBucket: 'adventureworks-61518.firebasestorage.app',
    iosBundleId: 'com.example.adventureWorks',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXpAz9PLjYdiG6mxoPq3Mdxc698nqC6Jc',
    appId: '1:470125849375:ios:476a53508c56f95ae21e2a',
    messagingSenderId: '470125849375',
    projectId: 'adventureworks-61518',
    storageBucket: 'adventureworks-61518.firebasestorage.app',
    iosBundleId: 'com.example.adventureWorks',
  );
}
